# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wb_comm_if.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wb_comm_if.proto',
  package='',
  serialized_pb='\n\x10wb_comm_if.proto\"-\n\x08WayPoint\x12\x10\n\x08\x44istance\x18\x01 \x02(\x01\x12\x0f\n\x07Heading\x18\x02 \x02(\x01\"y\n\x11WheelBotTelemetry\x12\x18\n\x10ObstacleDistance\x18\x01 \x02(\x01\x12\x0f\n\x07Heading\x18\x02 \x02(\x01\x12\x1d\n\x15\x44riveDistanceEstimate\x18\x03 \x02(\x01\x12\x1a\n\x12WayPointCmdReached\x18\x04 \x01(\x08')




_WAYPOINT = _descriptor.Descriptor(
  name='WayPoint',
  full_name='WayPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Distance', full_name='WayPoint.Distance', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Heading', full_name='WayPoint.Heading', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=65,
)


_WHEELBOTTELEMETRY = _descriptor.Descriptor(
  name='WheelBotTelemetry',
  full_name='WheelBotTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ObstacleDistance', full_name='WheelBotTelemetry.ObstacleDistance', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Heading', full_name='WheelBotTelemetry.Heading', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DriveDistanceEstimate', full_name='WheelBotTelemetry.DriveDistanceEstimate', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WayPointCmdReached', full_name='WheelBotTelemetry.WayPointCmdReached', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=67,
  serialized_end=188,
)

DESCRIPTOR.message_types_by_name['WayPoint'] = _WAYPOINT
DESCRIPTOR.message_types_by_name['WheelBotTelemetry'] = _WHEELBOTTELEMETRY

class WayPoint(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WAYPOINT

  # @@protoc_insertion_point(class_scope:WayPoint)

class WheelBotTelemetry(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WHEELBOTTELEMETRY

  # @@protoc_insertion_point(class_scope:WheelBotTelemetry)


# @@protoc_insertion_point(module_scope)
